### PR TITLE
Add support to specify Cadinality on the EventHubTrigger

### LINKED ISSUE #14: Event Hubs trigger doesn't support batch trigger
_From @jeffhollan on June 13, 2018 12:14_

The best practice for running functions at high scale is to pull in a batch of messages in a single execution (`EventData[]`).  For javascript this is described in the function.json as:

```json
{
...
"cardinality": "many"
}
```

1. The Java attribute should allow for a configurable flag to set cardinality to many
  * The generated function.json should include `"cardinality": "many"`
1. The host should be able to send and have serialized `EventData[]` to the Java worker

@asavaritayal @pragnagopa as FYI

_Copied from original issue: Azure/azure-functions-java-worker#122_

### PR DESCRIPTION
**Pull request by pragnagopa**
Fixes #14

### CODE REVIEW

**Comment by pragnagopa** [comment]
@jdneo - Maven plugin needs to updated to generate function.json with the cardinality
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs#trigger---configuration

**Comment by jdneo** [comment]
@pragnagopa Seems this will be another breaking change for the runtime.

Is there any ETA for the following actions?

**Comment by pragnagopa** [comment]
This is not a breaking change. It adds support to specify cardinality which allows trigger input to be received as an array

**Comment by jdneo** [comment]
Cool, I'll let you know when the template is updated. Tracking here: https://github.com/Microsoft/azure-maven-plugins/issues/330

**Comment by jeffhollan** [comment]
@pragnagopa is there a related PR around the type that is used when this is turned on?  Like a way for the Java worker to accept and send to a method that has like `List<EventData>` as the trigger type?

**Comment by pragnagopa** [comment]
@mhoeger is looking into https://github.com/Azure/azure-functions-host/pull/3170 . For out of proc languages, we do not have support for strong types like EventData. For this scenario, it would be a string[] array

**Pull request merged**
