### PR TITLE
Adding annotation to ServiceBusQueueTrigger and ServiceBusTopicTrigger

### PR DESCRIPTION
**Pull request by amamounelsayed**
ServiceBusQueueTrigger and ServiceBusTopicTrigger will have new annotation to support isSessionsEnabled.

The C# attributes is [IsSessionsEnabled](https://github.com/Azure/azure-functions-servicebus-extension/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/ServiceBusTriggerAttribute.cs#L89)

### CODE REVIEW

**Comment by pragnagopa** [comment]
@amamounelsayed  
- Please add link  to servicebus extension that has C# attributes
- Update description to include details on adding annotation to eanble sessions
- Create issue on maven plugin repo and add link here

cc @Flanker32 @jdneo

**Comment by amamounelsayed** [comment]
@pragnagopa When I tested on my machine,
With the generated library jar I got.
"bindings" : [ {
    "type" : "serviceBusTrigger",
    "direction" : "in",
    "name" : "message",
    "queueName" : "%SBQueueName%",
    "isSessionsEnabled" : true,
    "connection" : "AzureWebJobsServiceBus"
  } ]
=======================
If I did not specify the value there is no default value for isSessionsEnabled.
  "bindings" : [ {
    "type" : "serviceBusTrigger",
    "direction" : "in",
    "name" : "message",
    "queueName" : "%SBQueueName%",
    "connection" : "AzureWebJobsServiceBus"
  } ]
Is this the reason we need to update the plugin?

**Comment by pragnagopa** [comment]
thanks for testing. No plugin updates needed!

**Comment by amamounelsayed** [comment]
Closed for pull request https://github.com/Azure/azure-functions-java-library/pull/99

**Pull request closed without merging**
