### PR TITLE
Rename HttpWebHookType to WebHookType

### PR DESCRIPTION
**Pull request by pragnagopa**
Rename HttpWebHookType to WebHookType to match function.json property [binding-expressions---json-payloads](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#binding-expressions---json-payloads)

### CODE REVIEW

**Comment by brunoborges** [comment]
Are webhooks used with other triggers as well?

**Comment by pragnagopa** [comment]
webHook is a http callback and specific to httpTriggers.

**Comment by pragnagopa** [comment]
Since a webhook by definition is a http call back, appending http to the name feels redundant

**Comment by brunoborges** [comment]
It helps users quickly understand the purpose of the class without even needing to read the javadoc. All Http related classes and interfaces start with Http too, so there's that. But anyways, it is up to you. :-) I'm fine either way.

**Comment by pragnagopa** [comment]
renaming in favor of consistency across languages :)

**Pull request merged**
