### PR TITLE
[BrokenLinksH2]

### PR DESCRIPTION
**Pull request by mohitp930**

### CODE REVIEW

**Comment by mohitp930** [comment]
Global effort to fix broken links

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

**Comment by mohitp930** [comment]
@amamounelsayed Friendly reminder this pull request is ready for review. If there is a more appropriate person to contact, let me know. Thanks!

**Comment by mohitp930** [comment]
**Global effort to fix broken links** 

@kaibocai 

The C+E Skilling team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. I’d very much appreciate your timely review and feedback on the link changes I’ve suggested. Thanks!

**Review by kaibocai — APPROVED** [review]

**Comment by kaibocai** [comment]
LGTM! Thanks for your contribution. But the target branch seems not correct. Can you create a same pr target to dev branch? Thanks.

**Pull request merged**
